# Generated by CMake, DO NOT EDIT
# Custom rules for faderTests
.SUFFIXES: 
all: \
	faderTests_buildpart_0


faderTests_buildpart_0: 
	echo "Depend check for xcode"
	cd /common/workspaces/arduino/myLibraries && make -C /common/workspaces/arduino/myLibraries -f /common/workspaces/arduino/myLibraries/CMakeScripts/XCODE_DEPEND_HELPER.make PostBuild.faderTests
