# Generated by CMake, DO NOT EDIT
# Custom rules for ALL_BUILD
.SUFFIXES: 
all: \
	/common/workspaces/arduino/myLibraries/CMakeFiles/ALL_BUILD


/common/workspaces/arduino/myLibraries/CMakeFiles/ALL_BUILD: 
	echo ""
	echo Build\ all\ projects
