# Generated by CMake, DO NOT EDIT
# Custom rules for ZERO_CHECK
.SUFFIXES: 
all: \
	/common/workspaces/arduino/myLibraries/CMakeFiles/ZERO_CHECK


/common/workspaces/arduino/myLibraries/CMakeFiles/ZERO_CHECK: 
	echo ""
	make -f /common/workspaces/arduino/myLibraries/CMakeScripts/ReRunCMake.make
